roddymetanez/TheatreRoyale

src/FrontEnd/InputScanner.java
src/Hello/HelloWorld.java
src/Tests/package-info.java

Scanner Class tweak, adding int and doubles format to scanner
Also seeing how this works again...

ScannerClass Tweak

---

src/Hello/HelloWorld.java
src/controller/Engine.java
src/controller/Theatre.java
src/models/Concert.java
src/models/LiveMusic.java
src/models/Musical.java
src/models/Opera.java
src/models/Performance.java
src/models/Show.java
src/models/Theatre.java
src/models/alterLanguage.java
src/util/DBConnector.java
src/util/InputReader.java
src/util/Parser.java

Began work on the user interface, especially the M1 requirements for tomorrows call.

User interface start

---

src/controller/Theatre.java
src/models/Performance.java
src/models/Show.java
src/util/InputReader.java

Cleaned up and refactored initial commit code.

Refractor and cleaning up initial commit

---

src/sql/theater_system.sql

Minor changes to SQL following terminated Pull Request

Changes to SQL

---

src/controller/Theatre.java
src/models/Performance.java

Updated and refactored the the Theatre controller code to implement the new SQL procedures for M1 tasks.

M1 tasks implemented using the SQL procedures from Sylvia

---

src/sql/theatre_system.sql

Added:
- getShows
- getShowByName
- getShowByDate
3 new stored procedures:
- checkAvailability
- updateAvailability
- storeCustomerData

refactored theatre_system sql file

---

src/data_access/DBConnector.java
src/data_access/DataAccess.java
src/sql/theatre_system.sql

Repeat of last to see if we can avoid a rebase.

Not quite Small additions

---

src/models/Ticket.java

Get+Set Seating List methods added, as missing from last commit

Get+Set Seating List methods added

---

src/controller/Theatre.java

Formatted code to be more user readable
- Constructor and global variables placed at the top
- A method had duplicated half of itself, removed it.
- Currency symbol had been replaced with a <?> . Replaced with correct currency symbol

"Formatted code and removed a duplicated method"

---

src/Tests/UserInteractionTesting.java
src/controller/Theatre.java

inter branch merge incorporating #39, #40

inter branch merge

---

src/Tests/DataAccessTest.java
src/Tests/UserInteractionTesting.java
src/controller/Theatre.java
src/data_access/DBConnector.java
src/data_access/DataAccess.java
src/data_access/DataAccessTest.java
src/models/Basket.java
src/models/Patron.java
src/models/Ticket.java
src/util/Parser.java

DragAndDrop of DanN98 Main
Drag and Drop of Dan 98 Main

Code cleanup v2

---

src/models/AlterLanguage.java
src/models/LiveMusic.java

Interfaces
- LiveMusic
- AlterLanguage
were unused and have been removed completely

Removed unused interfaces

---

src/Tests/DataAccessTest.java
src/Tests/UserInteractionTesting.java
src/controller/Theatre.java
src/models/Basket.java
src/models/Patron.java
src/models/Ticket.java
src/sql/theatre_system.sql

WIP commit before 12pm conversation with Dan

WIP commit before 12pm conversation with Dan

---

src/models/AlterLanguage.java
src/models/LiveMusic.java
src/models/Patron.java

Patron Changes

---

src/controller/Theatre.java

Theare Changes

---

src/controller/Theatre.java

"Added method to request user details"

"Added method to request user details"

---

.gitignore
.project
src/controller/Theatre.java
src/data_access/DBConnector.java
src/data_access/DataAccess.java
src/data_access/DataAccessTest.java
src/models/Seat.java
src/models/Ticket.java
src/util/DateTimeConverter.java
src/util/InputReader.java

Update to seats method

---

src/controller/Theatre.java

Added extra message to printBasketMenu()

Added extra message to printBasketMenu()

---

src/models/Basket.java
src/models/Ticket.java

Basket clear

---

src/Tests/UserInteractionTesting.java
src/controller/Theatre.java
src/models/Ticket.java

Circle Count  & Stall count, test passing

Update To user interaction
